---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: seerr
  namespace: flux-system
spec:
  interval: 5m
  ref:
    tag: 2.7.0
  url: oci://ghcr.io/fallenbagel/jellyseerr/seerr-chart
