# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jCvXFU90iy0=,iv:Wdkqj/enKJqyf1xJhDXkGbornY9TdJA0VN1ADzjt3T0=,tag:pOhtN2yBYrDWXiJXpoFOKQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:sqhHkF6jg599OF0D7IX3FuuMINw2fH9R,iv:srO4QMNefZt7XhWeBRvWHG6Am90bqUzuC04HHmowdZQ=,tag:NDwhNSS7VEvGBTPibzVV4g==,type:str]
    NAS_IP: ENC[AES256_GCM,data:CCNz3k9E3sxe3lAz,iv:hcVsI7Yvp2siO93JzAeBIqmEZZk8hmxEkHhXHOGAyCY=,tag:AJHZFf9fS7Dk9YDsbJ7bgg==,type:str]
    DCSI_API_KEY: ENC[AES256_GCM,data:A1epNT+T9ThksJ8CP/Z9OOkPUkoj0HIEoVLoPL/cHOm7Z9Qo6PhYWohHD05V8iMShp5AbK0xM2YvBd4/CycDxTq/,iv:TN6qrzi6Da5gzCLcmtZ96qOGsqiWlhNI2vK2hFW40Kk=,tag:e8/Y10xcLT+tdRoPrGYOnA==,type:str]
    DCSI_USER: ENC[AES256_GCM,data:5WoA,iv:4QqjgfobSAIIB7jWkIAEFGc5Rao9eaHf/jQxWfn6qnE=,tag:Es6RBSMGeryiXlxjOUmuZQ==,type:str]
    DCSI_PASS: ENC[AES256_GCM,data:Rqf+tMG2BPQHhw==,iv:c75YdrBkQ7yqAniaIKCPeutPgsl9zVr6hKi5/l7auXA=,tag:aP3X/zm+s+2jLq9MIqrhYg==,type:str]
    Z2M_NETWORK_KEY: ENC[AES256_GCM,data:0jGatqJj7IjcHCczn8IhRozpRxrNoIjKNY+Da6VPyb+v0mkiuSbDtdXwNSuwLPDpSO7aTbg32BbP3EAqGeTcPAiwkXXcMlnV,iv:Kcq7FvbBXcDiGKSEbUEc/sbKUYgf41xbraO3q817Wmg=,tag:AfuhpTzOMuto5db/P1rJ/g==,type:str]
    EMQX_NAME: ENC[AES256_GCM,data:4ieGBqaAJMw=,iv:9xjvq1KVq9/+P6LAFWpPgqQZ0B9uP9v5voEPrFLPayk=,tag:ZD4DRMojV4vxDwvtvB9kBg==,type:str]
    EMQX_SECRET: ENC[AES256_GCM,data:/SnVuZcUcE5GTbM6WGg=,iv:k18zv5HPH3gvnqODwDtUkeNr0hLLllZi+jpzTvnz/jA=,tag:kehWMjRPlbptR0R/UI8z8w==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:P0O7Vwj1C7hp9dG0xZBohlEPNTG1oaki,iv:UtNR1+R6+4QRuPSLGOYD7Dcxw1B1ZiWCPItr43D6p6Y=,tag:KfI/oqT7Sw1kU8Ff4nMnJw==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:aXiMdzW/KyM=,iv:TiQ7x7WBF/jwnKb8/WAFC22+PRyrt5QnZ1+Y/aLr15w=,tag:dEguOrzqQMWmoNXAAjBujw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rXKXQsJF9yvR44nfIu4=,iv:J5Xvcv57jZca0dVwOcREz/fM/XR40x6v4ICVm5SJ7f4=,tag:xbzuWrPjWTVmWNBNfvi1YQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:E4xQWo8AdK4TbNn+9YUXrPDWkQFDB5GLHE1PQ1aZChE=,iv:C4ntqkHLp2gfWKTegAH6x1hvpZadKcb/Dl7jrbwVf2E=,tag:RJMk9vY6YruUPG611H48dA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:E0PeakjWEe1lCUefceL+P7vqWc1MmHDQfNutDVhtpuA=,iv:FruF4cYrZgBkmxj7EBYFl/DnztGn39OCJM5l8f0Jnro=,tag:ZVm5iAnS6ueSFTugK6lDMw==,type:str]
    TANDOOR_SECRET_KEY: ENC[AES256_GCM,data:HaNvyw+waFQZBrv83ED1Q249fWECzrAKhRTOJEctwHQvDlM5cLk5+BDm7wLOROlD8IuGl72IS3TIry7muAfSgg==,iv:qI2oFk4cGGOqguh+IETP4qg4EszbBtJfym++9O6OfyE=,tag:hE2WemTJauUI2yESjL+3TA==,type:str]
sops:
    age:
        - recipient: age1vcv85qmhme0zc9ncdvgw9mq0cr2fjewts3ne2g8xnngvpktwapxq5x9reu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R1VlSm15TzF2bHNYUkoz
            UXlka2orcWlBWEY5VXpvbTV1S283alBKUTFZCk9SdzFGTVRQN3dMSU1xWFJvdDJs
            alJtc3pneE52M1ROK2doaGt2YnBoZHcKLS0tIHZsRU1LR0htOVhlVkg3a2xPZXJ3
            UXBsUkdZL1k1MFgzVnVaeXhGeUp5NkkK7IDLfqy7JJ1mO2GDh2zS5t4Oh7qxB23F
            JJ2i+hWMKSMyugeRnG6jnr56uHvB67mWbfwQzy2asepk6Yo5aRt9ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:43:05Z"
    mac: ENC[AES256_GCM,data:Z9ZX36OpTsAj6OMCeYIWOCAF90xdl4c8KoScv+0d7DV3/fczG0V44F2pDsWU5Y8MILM1VIAF+DUjq4GN1vFXF3c/tDVO3C1XEg7OblZTmg4gQyn8g1ZNAwEyUw0eh8G2X4ZGvBBq1Q8TkNt94qFPMsw562T7jiH713xCFpOJaKY=,iv:HPIaTF6Gm9jGMrBEZzYGxfZV+WV2AXtfPqczV4D4H+E=,tag:0sf9B0cGo5uz8jKeIYvPlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
