---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy
  - cnpg
  - default
  - deluge
  - emqx/ks.yaml
  - flux-system
  - fusion
  - hajimari
  - home-assistant
  - homebox
  - immich
  - jackett
  - jellyfin
  - kapowarr
  - kube-prometheus-stack
  - kube-system
  - lidarr
  - loki
  - node-feature-discovery
  - nzbget
  - overseerr
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - recyclarr
  - seerr
  - sonarr
  - tautulli
  - zigbee2mqtt
  - zwave-js-ui
